//
//  ShareService.swift
//  Prompt
//
//  Handles sharing and exporting prompts
//

import Foundation
import UIKit
import PDFKit

enum ExportFormat: String, CaseIterable, Identifiable {
    case text = "Text"
    case markdown = "Markdown"
    case pdf = "PDF"

    var id: String { rawValue }

    var icon: String {
        switch self {
        case .text: return "doc.plaintext"
        case .markdown: return "text.badge.checkmark"
        case .pdf: return "doc.richtext"
        }
    }

    var fileExtension: String {
        switch self {
        case .text: return "txt"
        case .markdown: return "md"
        case .pdf: return "pdf"
        }
    }

    var mimeType: String {
        switch self {
        case .text: return "text/plain"
        case .markdown: return "text/markdown"
        case .pdf: return "application/pdf"
        }
    }
}

@MainActor
class ShareService {
    static let shared = ShareService()
    private init() {}

    // MARK: - Copy to Clipboard

    func copyToClipboard(_ text: String) {
        UIPasteboard.general.string = text
    }

    // MARK: - Share Enhanced Prompt

    func sharePrompt(original: String, enhanced: String, format: ExportFormat = .text) -> URL? {
        let content = formatPromptContent(original: original, enhanced: enhanced, format: format)

        switch format {
        case .text, .markdown:
            return saveToTempFile(content: content, extension: format.fileExtension)
        case .pdf:
            return generatePDF(original: original, enhanced: enhanced)
        }
    }

    // MARK: - Format Content

    private func formatPromptContent(original: String, enhanced: String, format: ExportFormat) -> String {
        let timestamp = DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .short)

        switch format {
        case .text:
            return """
            ORIGINAL PROMPT
            ===============
            \(original)

            ENHANCED PROMPT
            ===============
            \(enhanced)

            ---
            Generated by Promptomize
            \(timestamp)
            """

        case .markdown:
            return """
            # Prompt Enhancement

            ## Original Prompt

            \(original)

            ## Enhanced Prompt

            \(enhanced)

            ---

            *Generated by Promptomize on \(timestamp)*
            """

        case .pdf:
            return formatPromptContent(original: original, enhanced: enhanced, format: .text)
        }
    }

    // MARK: - Save to Temp File

    private func saveToTempFile(content: String, extension ext: String) -> URL? {
        let tempDir = FileManager.default.temporaryDirectory
        let fileName = "prompt_\(UUID().uuidString.prefix(8)).\(ext)"
        let fileURL = tempDir.appendingPathComponent(fileName)

        do {
            try content.write(to: fileURL, atomically: true, encoding: .utf8)
            return fileURL
        } catch {
            print("Failed to save temp file: \(error)")
            return nil
        }
    }

    // MARK: - Generate PDF

    private func generatePDF(original: String, enhanced: String) -> URL? {
        let pageWidth: CGFloat = 612  // US Letter
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 50

        let pdfMetaData = [
            kCGPDFContextCreator: "Promptomize",
            kCGPDFContextTitle: "Enhanced Prompt"
        ]

        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData as [String: Any]

        let renderer = UIGraphicsPDFRenderer(
            bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight),
            format: format
        )

        let tempDir = FileManager.default.temporaryDirectory
        let fileName = "prompt_\(UUID().uuidString.prefix(8)).pdf"
        let fileURL = tempDir.appendingPathComponent(fileName)

        do {
            try renderer.writePDF(to: fileURL) { context in
                context.beginPage()

                let contentWidth = pageWidth - 2 * margin
                var yOffset: CGFloat = margin

                // Title
                let titleFont = UIFont.boldSystemFont(ofSize: 24)
                let titleAttributes: [NSAttributedString.Key: Any] = [
                    .font: titleFont,
                    .foregroundColor: UIColor.black
                ]
                let title = "Prompt Enhancement"
                let titleRect = CGRect(x: margin, y: yOffset, width: contentWidth, height: 30)
                title.draw(in: titleRect, withAttributes: titleAttributes)
                yOffset += 50

                // Original section header
                let headerFont = UIFont.boldSystemFont(ofSize: 14)
                let headerAttributes: [NSAttributedString.Key: Any] = [
                    .font: headerFont,
                    .foregroundColor: UIColor.darkGray
                ]
                let originalHeader = "ORIGINAL PROMPT"
                let originalHeaderRect = CGRect(x: margin, y: yOffset, width: contentWidth, height: 20)
                originalHeader.draw(in: originalHeaderRect, withAttributes: headerAttributes)
                yOffset += 25

                // Original content
                let bodyFont = UIFont.systemFont(ofSize: 12)
                let bodyAttributes: [NSAttributedString.Key: Any] = [
                    .font: bodyFont,
                    .foregroundColor: UIColor.black
                ]
                let originalSize = original.boundingRect(
                    with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: bodyAttributes,
                    context: nil
                )
                let originalRect = CGRect(x: margin, y: yOffset, width: contentWidth, height: min(originalSize.height, 200))
                original.draw(in: originalRect, withAttributes: bodyAttributes)
                yOffset += min(originalSize.height, 200) + 30

                // Enhanced section header
                let enhancedHeader = "ENHANCED PROMPT"
                let enhancedHeaderRect = CGRect(x: margin, y: yOffset, width: contentWidth, height: 20)
                enhancedHeader.draw(in: enhancedHeaderRect, withAttributes: headerAttributes)
                yOffset += 25

                // Enhanced content
                let enhancedSize = enhanced.boundingRect(
                    with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: bodyAttributes,
                    context: nil
                )
                let enhancedRect = CGRect(x: margin, y: yOffset, width: contentWidth, height: min(enhancedSize.height, pageHeight - yOffset - 100))
                enhanced.draw(in: enhancedRect, withAttributes: bodyAttributes)

                // Footer
                let footerFont = UIFont.italicSystemFont(ofSize: 10)
                let footerAttributes: [NSAttributedString.Key: Any] = [
                    .font: footerFont,
                    .foregroundColor: UIColor.gray
                ]
                let timestamp = DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .short)
                let footer = "Generated by Promptomize • \(timestamp)"
                let footerRect = CGRect(x: margin, y: pageHeight - 40, width: contentWidth, height: 20)
                footer.draw(in: footerRect, withAttributes: footerAttributes)
            }
            return fileURL
        } catch {
            print("Failed to generate PDF: \(error)")
            return nil
        }
    }

    // MARK: - Present Share Sheet

    func presentShareSheet(items: [Any], from viewController: UIViewController? = nil) {
        let activityController = UIActivityViewController(activityItems: items, applicationActivities: nil)

        if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let rootVC = windowScene.windows.first?.rootViewController {
            let presenter = viewController ?? rootVC
            presenter.present(activityController, animated: true)
        }
    }
}
