#!/bin/bash

# Setup UI Test Target for Fastlane Screenshots
# This script provides instructions for adding the UI test target in Xcode

echo "=========================================="
echo "Fastlane Screenshot Setup Instructions"
echo "=========================================="
echo ""
echo "The UI test files have been created in PromptUITests/"
echo ""
echo "To complete setup, you need to add a UI Test target in Xcode:"
echo ""
echo "1. Open Prompt.xcodeproj in Xcode"
echo ""
echo "2. Add UI Test Target:"
echo "   - File > New > Target..."
echo "   - Select 'UI Testing Bundle'"
echo "   - Product Name: PromptUITests"
echo "   - Target to be Tested: Prompt"
echo "   - Click Finish"
echo ""
echo "3. Add existing files to the target:"
echo "   - In Project Navigator, right-click on PromptUITests folder"
echo "   - Select 'Add Files to \"Prompt\"...'"
echo "   - Select all files in PromptUITests/ directory"
echo "   - Make sure 'PromptUITests' target is checked"
echo "   - Click Add"
echo ""
echo "4. Delete the auto-generated test file:"
echo "   - Xcode creates a default test file, delete it if present"
echo ""
echo "5. Build the UI test scheme:"
echo "   - Select PromptUITests scheme"
echo "   - Build (Cmd+B)"
echo ""
echo "6. Run screenshots:"
echo "   - cd to project root"
echo "   - Run: fastlane screenshots"
echo ""
echo "=========================================="
